.PHONY: insecure_server
insecure_server:
	cmd /C start cmd /k "go run ./cmd/insecure_server/main.go"

.PHONY: insecure_client
insecure_client:
	cmd /C start cmd /k "go run ./cmd/insecure_client/main.go"